server:
  port: 8083  # Unique port for notification-service

spring:
  application:
    name: notification-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  # Use Docker network name for internal communication
    register-with-eureka: true
    fetch-registry: true
