server :
  port: 8084

spring :
  application :
    name : common-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  # Use Docker network name for internal communication
    register-with-eureka: true
    fetch-registry: true
