version: '3.8'

services:
  # Traefik Gateway
  traefik:
    image: traefik:v2.9
    command:
      - --api.insecure=false
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"  # Traefik Dashboard on port 8081
    networks:
      - flowcent-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Account Service
  account-service:
    container_name: account-service
    build:
      context: ./account-service  # Matches the project structure
      dockerfile: Dockerfile      # Ensure Dockerfile exists inside account-service directory
    networks:
      - flowcent-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account-service.rule=PathPrefix(`/accounts`)"
      - "traefik.http.services.account-service.loadbalancer.server.port=8085"  # Unique port to avoid conflict

  # Transaction Service
  transaction-service:
    container_name: transaction-service
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - flowcent-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transaction-service.rule=PathPrefix(`/transactions`)"
      - "traefik.http.services.transaction-service.loadbalancer.server.port=8082"  # Unique port

  # Notification Service
  notification-service:
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - flowcent-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notification-service.rule=PathPrefix(`/notifications`)"
      - "traefik.http.services.notification-service.loadbalancer.server.port=8083"  # Unique port

# Common Service
  common-service:
    container_name: common-service
    build:
      context: ./common-service
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - flowcent-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.common-service.rule=PathPrefix(`/common`)"
      - "traefik.http.services.common-service.loadbalancer.server.port=8084"

    #auth-service
  auth-service :
    container_name: auth-service
    build :
      context : ./auth-service
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - flowcent-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.auth-service.loadbalancer.server.port=8086"

  # Eureka Server
  eureka-server:
    build:
      context: ./eureka-server  # Matches your project structure
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    container_name: eureka-server
    ports:
      - "8761:8761"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eureka.rule=Host(`eureka.localhost`)"
      - "traefik.http.services.eureka.loadbalancer.server.port=8761"
    networks:
      - flowcent-network

networks:
  flowcent-network:
    driver: bridge
