server:
  port: 8082

spring:
  application:
    name: transaction-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  # Use Docker network name for internal communication
    register-with-eureka: true
    fetch-registry: true
