spring:
  datasource:
    url: jdbc:postgresql://prod-db-host:5432/transactiondb
    driver-class-name: org.postgresql.Driver
    username: prod_user
    password: smk_123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    root: warn