## use openjdk 21 as the base image
#FROM openjdk:21-jdk-slim
## set the working dorectory inside the container
#VOLUME /tmp
#
## copy theJAR file built by maven into the container
#ARG JAR_FILE=target/transaction-service-0.0.1-SNAPSHOT.jar
#
#COPY ${JAR_FILE} app.jar
#
## runtime application
#ENTRYPOINT ["java", "-jar", "/app.jar"]
#
#
#
#
