server:
  port: 8081  # Unique port for account-service

spring:
  application:
    name: account-service  # Service name to register with Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL of Eureka server
    register-with-eureka: true
    fetch-registry: true