server:
  port: 8085  # Unique port for account-service

spring:
  application:
    name: account-service  # Service name to register with Eureka

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  # Use Docker network name for internal communication
    register-with-eureka: true
    fetch-registry: true

